esc set fullscreen no
space cycle pause
mbtn_left cycle pause
wheel_up add volume 5
wheel_down add volume -5
alt+left frame-back-step
alt+right frame-step
left seek -1
right seek 1
shift+left seek -3
shift+right seek 3
pgup seek -10
pgdwn seek 10
up add volume 10
down add volume -10
enter cycle fullscreen
f11 cycle fullscreen
kp_enter cycle fullscreen
s screenshot video
S screenshot
home seek 0 absolute-percent+exact
end seek 100 absolute-percent+exact
- add speed -0.05
+ add speed 0.05
a add sub-delay -0.1
d add sub-delay +0.1
i script-binding stats/display-stats-toggle
