slang=chi,zho
save-position-on-quit
watch-later-options-add=volume
watch-later-options-remove=pause
ignore-path-in-watch-later-config
volume-max=100
audio-file-auto=fuzzy
sub-auto=fuzzy
keep-open=yes
no-input-default-bindings
screenshot-tag-colorspace
screenshot-template="%F_%P_%n"
profile=gpu-hq
icc-profile-auto
blend-subtitles=video
video-sync=display-resample
interpolation
tscale=oversample
osc=no
osd-bar=no
border=no
